name: Release

on:
  push:
    tags:
      - "*"
jobs:
  build_linux:
    name: Build the Tool for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      # Go Setup
      - name: Setup Go
        uses: actions/checkout@v2
      # Build
      - name: Install Deps
        run: |
          mkdir out
          cd out
          go build ..
          cd ..

      - name: Bundle
        uses: actions/upload-artifact@v2
        with:
          name: edselfheatmap-linux
          path: "./out"

  build_win:
    name: Build the Tool for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      # Go Setup
      - name: Setup Go
        uses: actions/checkout@v2
      # Build
      - name: Install Deps
        run: |
          mkdir out
          cd out
          go build ..
          cd ..

      - name: Bundle
        uses: actions/upload-artifact@v2
        with:
          name: edselfheatmap-windows
          path: "./out"


  publish:
    needs:
      - build_linux
      - build_win
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: edselfheatmap-windows
          path: "./out/win"
      - uses: actions/download-artifact@master
        with:
          name: edselfheatmap-linux
          path: "./out/linux"
      - name: ZIP up
        run: |
          zip -r windows.zip ./out/win
          zip -r linux.zip ./out/linux
      - name: List
        run: |
          tree
      - uses: ncipollo/release-action@v1
        with:
          artifacts: windows.zip, linux.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
